<?php

namespace App\Modules\Admin\Controllers;

use Illuminate\Http\Request;
use TCG\Voyager\Facades\Voyager;
use \TCG\Voyager\Http\Controllers\VoyagerBaseController;

class VoyagerInfoController extends VoyagerBaseController
{
    public function create(Request $request)
    {
        return parent::create($request); // TODO: Change the autogenerated stub
    }

    public function edit(Request $request, $id)
    {
        dd(1);
        return parent::edit($request, $id); // TODO: Change the autogenerated stub
    }
}
