<?php

namespace App\Modules\Admin\Controllers;

use Illuminate\Http\Request;
use TCG\Voyager\Facades\Voyager;
use \TCG\Voyager\Http\Controllers\VoyagerBaseController;
use TCG\Voyager\Http\Controllers\VoyagerController;

class VoyagerDashboardController extends VoyagerController
{
    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }
}
